# @format

version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  # nginx
  web:
    image: nginx:1.18-alpine
    ports:
      - 1002:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  #mysql
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
